# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"\x0e\n\x0c\x45mptyMessage\"\x16\n\x04Time\x12\x0e\n\x06period\x18\x01 \x01(\x05\"$\n\x08NodeInfo\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\")\n\nLeaderInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"*\n\nVoteResult\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\x08\x32\xa3\x01\n\x0bRaftService\x12\'\n\tGetLeader\x12\r.EmptyMessage\x1a\x0b.LeaderInfo\x12\x1f\n\x07Suspend\x12\x05.Time\x1a\r.EmptyMessage\x12!\n\x07\x41skVote\x12\t.NodeInfo\x1a\x0b.VoteResult\x12\'\n\rAppendEntries\x12\t.NodeInfo\x1a\x0b.VoteResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYMESSAGE._serialized_start=14
  _EMPTYMESSAGE._serialized_end=28
  _TIME._serialized_start=30
  _TIME._serialized_end=52
  _NODEINFO._serialized_start=54
  _NODEINFO._serialized_end=90
  _LEADERINFO._serialized_start=92
  _LEADERINFO._serialized_end=133
  _VOTERESULT._serialized_start=135
  _VOTERESULT._serialized_end=177
  _RAFTSERVICE._serialized_start=180
  _RAFTSERVICE._serialized_end=343
# @@protoc_insertion_point(module_scope)
